---
performance:
  predict_forward: 5000
  n_jobs: 64
  n_jobs_optimiser: 1
  inner_max_num_threads: 10
experience:
  random_state: 42
evaluation_params:
  n_early_stopping: 2
  end_train_idx: 10000
  batch_size: 1000
  rolling: False
  significance: 0.0
  metric:
    name: mcc
  n_score: 2
dataset:
  name: electricity
common_detectors_params:
  batch_size: 1000
  period: 1000
common_runs_params:
  delays:
    label: 0
    drift: 0
    retraining: 0
runs:
# ------------ NO Drift
  - name: no_detection
    type: baseline
    detectors:
      - name: no_detection
    model:
      source: drift_study.model_arch.tree_model
      name: rf_classifier
    train_all_data: False
  - name: no_detection_opt
    type: baseline
    detectors:
      - name: no_detection
    model:
      source: drift_study.model_arch.tree_model
      name: opt_rf_classifier
    train_all_data: False
# # ------------ Periodic
  - name: periodic
    type: baseline
    detectors:
      - name: periodic
    model:
      source: drift_study.model_arch.tree_model
      name: rf_classifier
    train_all_data: False
  - name: periodic_all
    type: baseline
    detectors:
      - name: periodic
    model:
      source: drift_study.model_arch.tree_model
      name: rf_classifier
    train_all_data: True
  - name: at_15_opt
    type: baseline
    detectors:
      - name: periodic
        params:
          period: 5000
    model:
      source: drift_study.model_arch.tree_model
      name: opt_rf_classifier
    train_all_data: False
  - name: at_15_all_opt
    type: baseline
    detectors:
      - name: periodic
        params:
          period: 5000
    model:
      source: drift_study.model_arch.tree_model
      name: opt_rf_classifier
    train_all_data: True
  - name: at_20_opt
    type: baseline
    detectors:
      - name: periodic
        params:
          period: 10000
    model:
      source: drift_study.model_arch.tree_model
      name: opt_rf_classifier
    train_all_data: False
  - name: at_20_all_opt
    type: baseline
    detectors:
      - name: periodic
        params:
          period: 10000
    model:
      source: drift_study.model_arch.tree_model
      name: opt_rf_classifier
    train_all_data: True
  - name: at_28_opt
    type: baseline
    detectors:
      - name: periodic
        params:
          period: 18000
    model:
      source: drift_study.model_arch.tree_model
      name: opt_rf_classifier
    train_all_data: False
  - name: at_28_all_opt
    type: baseline
    detectors:
      - name: periodic
        params:
          period: 18000
    model:
      source: drift_study.model_arch.tree_model
      name: opt_rf_classifier
    train_all_data: True
