version: 1
disable_existing_loggers: false
objects:
  queue:
    class: queue.Queue
    maxsize: 1000
formatters:
  simple:
    format: '[%(levelname)s|%(name)s|%(module)s|L%(lineno)d] %(asctime)s: %(message)s'
    datefmt: '%Y-%m-%dT%H:%M:%S%z'
handlers:
  stderr:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stderr
  zqueue_handler:
    (): mlc.logging.queue_listner_handler.QueueListenerHandler
    handlers:
    - cfg://handlers.stderr
    respect_handler_level: true
loggers:
  '':
    level: INFO
    handlers:
    - zqueue_handler
  'mlc.models.torch_models':
    level: INFO
    # propagate: false
