---
common_params:
  window_size: 100000
  batch_size: 5000
  random_state: 42
  p_value: 0.05
  period: 5000
performance_params:
  predict_forward: 50000
  n_jobs: 10
runs:
  - dataset_name: lcld
    model_name: random_forest
    drift_name: no_drift
    label_delay: 0
    drift_delay: 0
    retraining_delay: 0
  - dataset_name: lcld
    model_name: random_forest
    drift_name: periodic
    label_delay: 0
    drift_delay: 0
    retraining_delay: 0
  - run_name: adwin
    dataset_name: lcld
    model_name: random_forest
    drift_name:
      - n_batch
      - adwin
    label_delay: 0
    drift_delay: 0
    retraining_delay: 0
  - run_name: adwin_delayed
    dataset_name: lcld
    model_name: random_forest
    drift_name:
      - n_batch
      - adwin
    label_delay: 10days
    drift_delay: 0
    retraining_delay: 1W
  - run_name: evidently
    dataset_name: lcld
    model_name: random_forest
    drift_name:
      - n_batch
      - evidently
    label_delay: 0
    drift_delay: 0
    retraining_delay: 0
  - run_name: evidently_delayed
    dataset_name: lcld
    model_name: random_forest
    drift_name:
      - n_batch
      - evidently
    label_delay: 10days
    drift_delay: 0
    retraining_delay: 1W
