---
common_params:
  window_size: 100000
  batch_size: 5000
  random_state: 42
  p_value: 0.05
  period: 5000
performance_params:
  predict_forward: 5000
  n_jobs: 10
evaluation_params:
  reference_methods:
    - no_drift
    - periodic
  batch_size: 5000
  rolling: False
runs:
  - run_name: no_drift
    dataset_name: lcld_v2
    model_name: random_forest
    drift_name: no_drift
    label_delay: 0
    drift_delay: 0
    retraining_delay: 0
  - run_name: periodic
    dataset_name: lcld_v2
    model_name: random_forest
    drift_name: periodic
    label_delay: 0
    drift_delay: 0
    retraining_delay: 0
  - run_name: adwin_no_batch
    dataset_name: lcld_v2
    model_name: random_forest
    drift_name:
      - adwin_error
    label_delay: 0
    drift_delay: 0
    retraining_delay: 0
  - run_name: adwin_delayed
    dataset_name: lcld_v2
    model_name: random_forest
    drift_name:
      - n_batch
      - adwin_error
    label_delay: 10days
    drift_delay: 0
    retraining_delay: 1W
  - run_name: evidently
    dataset_name: lcld_v2
    model_name: random_forest
    drift_name:
      - n_batch
      - evidently
    label_delay: 0
    drift_delay: 0
    retraining_delay: 0
  - run_name: evidently_delayed
    dataset_name: lcld_v2
    model_name: random_forest
    drift_name:
      - n_batch
      - evidently
    label_delay: 10days
    drift_delay: 0
    retraining_delay: 1W
  - run_name: rf_uncertainty
    dataset_name: lcld_v2
    model_name: random_forest
    drift_name:
      - n_batch
      - rf_uncertainty
      - adwin
    label_delay: 0
    drift_delay: 0
    retraining_delay: 0
    drift_parameters:
      uncertainty_type: total
  - run_name: rf_uncertainty_delayed
    dataset_name: lcld_v2
    model_name: random_forest
    drift_name:
      - n_batch
      - rf_uncertainty
      - adwin
    label_delay: 10days
    drift_delay: 0
    retraining_delay: 1W
    drift_parameters:
      uncertainty_type: total
  - run_name: rf_uncertainty_epistemic
    dataset_name: lcld_v2
    model_name: random_forest
    drift_name:
      - n_batch
      - rf_uncertainty
      - adwin
    label_delay: 0
    drift_delay: 0
    retraining_delay: 0
    drift_parameters:
      uncertainty_type: epistemic
  - run_name: rf_uncertainty_epistemic_delayed
    dataset_name: lcld_v2
    model_name: random_forest
    drift_name:
      - n_batch
      - rf_uncertainty
      - adwin
    label_delay: 10days
    drift_delay: 0
    retraining_delay: 1W
    drift_parameters:
      uncertainty_type: epistemic
  - run_name: rf_uncertainty_aleatoric
    dataset_name: lcld_v2
    model_name: random_forest
    drift_name:
      - n_batch
      - rf_uncertainty
      - adwin
    label_delay: 0
    drift_delay: 0
    retraining_delay: 0
    drift_parameters:
      uncertainty_type: aleatoric
  - run_name: rf_uncertainty_aleatoric_delayed
    dataset_name: lcld_v2
    model_name: random_forest
    drift_name:
      - n_batch
      - rf_uncertainty
      - adwin
    label_delay: 10days
    drift_delay: 0
    retraining_delay: 1W
    drift_parameters:
      uncertainty_type: aleatoric
  - run_name: rf_uncertainty_epistemic_evidently_delayed
    dataset_name: lcld_v2
    model_name: random_forest
    drift_name:
      - n_batch
      - rf_uncertainty
      - evidently
    label_delay: 10days
    drift_delay: 0
    retraining_delay: 1W
    drift_parameters:
      uncertainty_type: epistemic
