---
window_size: 5000
performance:
  predict_forward: 5000
  n_jobs: 10
experience:
  random_state: 42
evaluation_params:
  reference_methods:
    - no_drift
    - periodic
  batch_size: 1000
  rolling: False
  significance: 0.0
  metric:
    name: f1
dataset:
  name: electricity
common_detectors_params:
  p_value: 0.05
  period: 1000
runs:
#  - name: no_drift
#    model:
#      name: linear_model
#      source: linear_model
#    detectors:
#      - name: no_drift
#        params: {}
#    label_delay: 0
#    drift_delay: 0
#    retraining_delay: 0
  - name: periodic
    model:
      name: linear_model
      source: linear_model
    detectors:
      - name: periodic
        params: { }
    label_delay: 0
    drift_delay: 0
    retraining_delay: 0
