---
window_size: 5000
performance:
  predict_forward: 5000
  n_jobs: 10
  n_jobs_optimiser: 17
  inner_max_num_threads: 10
experience:
  random_state: 42
evaluation_params:
  batch_size: 1000
  rolling: False
  significance: 0.0
  metric:
    name: mcc
  n_score: 2
dataset:
  name: electricity
common_detectors_params:
  batch_size: 1000
common_runs_params:
  delays:
    label: 10days
    drift: 0
    retraining: 1W
trial_params:
  n_trials: 100
  period:
    min: 1000
    max: 20000
  model_type: random_forest
