---
window_size: 100000
performance:
  predict_forward: 50000
  n_jobs: 14
experience:
  random_state: 42
evaluation_params:
  reference_methods:
    - no_drift
    - periodic
  batch_size: 10000
  rolling: False
  significance: 0.0
  metric:
    name: f1
  n_score: 2
dataset:
  name: flight_delay_ord_classification
common_detectors_params:
  p_value: 0.05
  period: 10000
runs:
  - name: no_drift
    model:
      source: drift_study.model_arch.tree_model
      name: rf_classifier
    detectors:
      - name: no_drift
        params: {}
    label_delay: 0
    drift_delay: 0
    retraining_delay: 0
  - name: periodic
    model:
      source: drift_study.model_arch.tree_model
      name: rf_classifier
    detectors:
      - name: periodic
        params: {}
    label_delay: 0
    drift_delay: 0
    retraining_delay: 0
