---
sub_dir_path: manual400
performance:
  predict_forward: 1000000
  n_jobs:
    model: 128
    simulator: 1
evaluation_params:
  batch_size: 20000
  metric:
    name: mcc
  n_score: 2
dataset:
  name: lcld_201317_ds_time
common_detectors_params: {}
common_runs_params:
  training_step_size: 5000
  test_start_idx: 400000
  random_state: 42
  train_window_size: 0
  delays:
    label: 0
    drift: 0
    retraining: 0
runs:
  - name: manual
    type: baseline
    detectors:
      - name: no_detection
        params: {}
    model:
      source: drift_study.model_arch.tree_model
      name:
        grid: [rf_lcld, opt_rf_classifier]
    test_start_idx:
      grid: [400000, 420000, 600000, 800000, 860000, 940000]
    first_train_window_size:
      grid: [400000, -1]
