---
performance:
  predict_forward: 50000
  n_jobs:
    simulator: 1
    model: -1
evaluation_params:
  n_early_stopping: 2
  batch_size: 10000
  rolling: False
  significance: 0.0
  metric:
    name: mcc
  n_score: 2
dataset:
  name: lcld_201317_ds_time
common_detectors_params:
  batch_size: 10000
  period: 10000
common_runs_params:
  training_step_size: 5000
  train_window_size: -1
  first_train_window_size: -1
  test_start_idx: 400000
  random_state: 42
  delays:
    label: 0
    drift: 0
    retraining: 0
runs:
# ------------ NO Drift
  - name: no_detection
    type: baseline
    detectors:
      - name: no_detection
    model:
      source: drift_study.model_arch.tree_model
      name: rf_lcld
    train_all_data: False
  - name: no_detection_opt
    type: baseline
    detectors:
      - name: no_detection
    model:
      source: drift_study.model_arch.tree_model
      name: opt_rf_classifier
# ------------ Periodic
  - name: periodic
    type: baseline
    detectors:
      - name: periodic
        params:
          period: 2500
    model:
      source: drift_study.model_arch.tree_model
      name: rf_lcld
    train_window_size: 400000
  - name: periodic_all
    type: baseline
    detectors:
      - name: periodic
    model:
      source: drift_study.model_arch.tree_model
      name: rf_lcld
