---
window_size: 100000
performance:
  predict_forward: 50000
  n_jobs: 10
  n_jobs_optimiser: -40
experience:
  random_state: 42
evaluation_params:
  batch_size: 25000
  rolling: False
  significance: 0.0
  metric:
    name: mcc
  n_score: 2
dataset:
  name: lcld_201317_ds_time
common_detectors_params:
  batch_size: 1000
common_runs_params:
  delays:
    label: 10days
    drift: 0
    retraining: 1W
trial_params:
  n_trials: 100
  period:
    min: 5000
    max: 500000
