---
performance:
  predict_forward: 50000
  n_jobs: 20
  n_jobs_optimiser: 1
  inner_max_num_threads: 10
experience:
  random_state: 42
evaluation_params:
  end_train_idx: 100000
  batch_size: 25000
  rolling: False
  significance: 0.0
  metric:
    name: mcc
  n_score: 2
dataset:
  name: lcld_201317_ds_time
common_detectors_params:
  batch_size: 5000
common_runs_params:
  train_all_data: False
  delays:
    label: 10days
    drift: 0
    retraining: 4W
trial_params:
  n_trials: 100
  period:
    min: 5000
    max: 500000
  model_type: random_forest
