---
performance:
  predict_forward: 10000
  n_jobs:
    model: 10
    optimizer: 4
    k_fold: 3
experience:
  random_state: 42
evaluation_params:
  batch_size: 25000
  metric:
    name: mcc
  n_score: 2
  n_splits: 5
dataset:
  name: lcld_201317_ds_time
common_detectors_params:
  batch_size: 5000
common_runs_params:
  end_train_idx: 300000
  train_all_data: False
  delays:
    label: 10days
    drift: 0
    retraining: 4W
trial_params:
  n_trials: 100
  period:
    min: 5000
    max: 300000
  model_type: random_forest
