---
name: lcld_201317_ds_time
dataset: 
  name: lcld_201317_ds_time
models:
  - source: drift_study.model_arch.tree_model
    name: rf_scaled
    metadata: true
model:
  source: drift_study.model_arch.tree_model
  name: rf_scaled
  metadata: true
detectors:
  - name: divergence
first_train_window_size: -1
train_window_size: [200000]
periods: [20000, 50000, 100000, 200000]
test_start_idx: 400000
training_step_size: 5000
common_detectors_params:
  - batch_size: 5000
delays:
  drift: 0
  label: 10days
  retraining: 4W
optimization_iter:
  model: 10
  detector: 100
metric:
  name: mcc
predict_forward: 5000