---
train_dataset:
  name: lcld_201317_ds_time
n_train: 400000
train_cache:
  divergence:
    type: parquet
    params:
      path: ./data/drift_prod/divergence_cache.parquet
  uncertainty:
    type: parquet
    params:
      path: ./data/drift_prod/uncertainty_cache.parquet
model_path: ./data/drift_prod/models/lcld_test_rf.joblib
hotstart_dataset:
  name: lcld_201317_ds_time
  data:
    source:
      sql:
        connection_string: postgresql://postgres:example@localhost/lcld
        query: |
          SELECT
            *
          FROM
            x_data
        preprocess_module: drift_study.prod.preprocess_hotstart
  metadata:
    source:
      file:
        path: ./data/mlc/lcld_201317_ds/lcld_201317_ds_metadata.csv
  tasks:
    - name: unavailable
      task_type: classification
      evaluation_metric: mcc
  sorter: 
    date: date
hoststart_freq: 1day
testing_window: 13W
date_round: D
test_dataset:
  name: lcld_201317_ds_time
  data:
    source:
      sql:
        connection_string: postgresql://postgres:example@localhost/lcld
        query: |
          SELECT
            *
          FROM
            x_data
        preprocess_module: drift_study.prod.preprocess
  metadata:
    source:
      file:
        path: ./data/mlc/lcld_201317_ds/lcld_201317_ds_metadata.csv
  tasks:
    - name: unavailable
      task_type: classification
      evaluation_metric: mcc
  sorter: 
    date: date
loggers:
  - type: postgres
    params:
      db_url: postgresql://postgres:example@localhost/lcld
      db_table: drift_second
  - type: csv
    params:
      path: ./data/drift_prod/logs/lcld_metrics.csv
  - type: parquet
    params:
      path: ./data/drift_prod/logs/lcld_metrics.parquet
