---
window_size: 100000
performance:
  predict_forward: 5000
  n_jobs: 14
experience:
  random_state: 42
evaluation_params:
  reference_methods:
    - no_drift
    - periodic
  batch_size: 5000
  rolling: False
  significance: 0.0
  metric:
    name: f1
  n_score: 2
dataset:
  name: lcld_201317_time
common_detectors_params:
  p_value: 0.05
  period: 5000
runs:
  - name: no_drift
    model:
      source: drift_study.model_arch.tree_model
      name: rf_lcld
    detectors:
      - name: no_drift
        params: {}
    label_delay: 0
    drift_delay: 0
    retraining_delay: 0
  - name: periodic
    model:
      source: drift_study.model_arch.tree_model
      name: rf_lcld
    detectors:
      - name: periodic
        params: {}
    label_delay: 0
    drift_delay: 0
    retraining_delay: 0
  - name: adwin_error
    model:
      source: drift_study.model_arch.tree_model
      name: rf_lcld
    detectors:
      - name: metric
        params:
          metric_conf:
            name: proba_error
      - name: adwin
        params: { }
    label_delay: 0
    drift_delay: 0
    retraining_delay: 0
  - name: adwin_error_D
    model:
      source: drift_study.model_arch.tree_model
      name: rf_lcld
    detectors:
      - name: metric
        params:
          metric_conf:
            name: proba_error
      - name: adwin
        params: { }
    label_delay: 10days
    drift_delay: 0
    retraining_delay: 1W
  - name: ddm_error_D
    model:
      source: drift_study.model_arch.tree_model
      name: rf_lcld
    detectors:
      - name: metric
        params:
          metric_conf:
            name: class_error
      - name: ddm
        params:
          ddm_args:
            out_control_level: 1.5
    label_delay: 10days
    drift_delay: 0
    retraining_delay: 1W
  - name: eddm_error_D
    model:
      source: drift_study.model_arch.tree_model
      name: rf_lcld
    detectors:
      - name: metric
        params:
          metric_conf:
            name: class_error
      - name: eddm
        params: {}
    label_delay: 10days
    drift_delay: 0
    retraining_delay: 1W
  - name: data_D
    model:
      source: drift_study.model_arch.tree_model
      name: rf_lcld
    detectors:
      - name: n_batch
        params:
          batch_size: 5000
      - name: evidently
        params: {}
    label_delay: 10days
    drift_delay: 0
    retraining_delay: 1W
  - name: uncertainty_total_D
    model:
      source: drift_study.model_arch.tree_model
      name: rf_lcld
    detectors:
      - name: n_batch
        params:
          batch_size: 5000
      - name: rf_uncertainty
        params:
          uncertainty_type: total
      - name: adwin
        params: { }
    label_delay: 10days
    drift_delay: 0
    retraining_delay: 1W
  - name: uncertainty_epistemic_D
    model:
      source: drift_study.model_arch.tree_model
      name: rf_lcld
    detectors:
      - name: n_batch
        params:
          batch_size: 5000
      - name: rf_uncertainty
        params:
          uncertainty_type: epistemic
      - name: adwin
        params: { }
    label_delay: 10days
    drift_delay: 0
    retraining_delay: 1W
  - name: uncertainty_aleatoric_D
    model:
      source: drift_study.model_arch.tree_model
      name: rf_lcld
    detectors:
      - name: n_batch
        params:
          batch_size: 5000
      - name: rf_uncertainty
        params:
          uncertainty_type: aleatoric
      - name: adwin
        params: { }
    label_delay: 10days
    drift_delay: 0
    retraining_delay: 1W
#  - name: periodic_delay
#    model:
#      source: drift_study.model_arch.tree_model
#      name: rf_lcld
#    detectors:
#      - name: periodic
#        params: { }
#    label_delay: 10days
#    drift_delay: 0
#    retraining_delay: 1W
#  - name: adwin_no_batch
#    model:
#      name: rf_lcld
#    detectors:
#      - name: adwin_error
#        params: {}
#    label_delay: 0
#    drift_delay: 0
#    retraining_delay: 0
#  - name: adwin_no_delay
#    model:
#      name: rf_lcld
#    detectors:
#      - name: n_batch
#        params:
#          batch_size: 5000
#      - name: adwin_error
#        params: { }
#    label_delay: 0
#    drift_delay: 0
#    retraining_delay: 0
#  - name: adwin
#    model:
#      name: rf_lcld
#    detectors:
#      - name: adwin_error
#        params: { }
#    label_delay: 10days
#    drift_delay: 0
#    retraining_delay: 1W
#  - name: data
#    model:
#      name: rf_lcld
#    detectors:
#      - name: n_batch
#        params:
#          batch_size: 5000
#      - name: evidently
#        params: {}
#    label_delay: 10days
#    drift_delay: 0
#    retraining_delay: 1W
#  - name: uncertainty_total
#    model:
#      name: rf_lcld
#    detectors:
#      - name: rf_uncertainty
#        params:
#          uncertainty_type: total
#      - name: adwin
#        params: {}
#    label_delay: 10days
#    drift_delay: 0
#    retraining_delay: 1W
#  - name: uncertainty_total_batch
#    model:
#      name: rf_lcld
#    detectors:
#      - name: n_batch
#        params:
#          batch_size: 5000
#      - name: rf_uncertainty
#        params:
#          uncertainty_type: total
#      - name: adwin
#        params: { }
#    label_delay: 10days
#    drift_delay: 0
#    retraining_delay: 1W
#  - name: uncertainty_epistemic_batch
#    model:
#      name: rf_lcld
#    detectors:
#      - name: n_batch
#        params:
#          batch_size: 5000
#      - name: rf_uncertainty
#        params:
#          uncertainty_type: epistemic
#      - name: adwin
#        params: { }
#    label_delay: 10days
#    drift_delay: 00
#    retraining_delay: 1W
#  - name: uncertainty_aleatoric_batch
#    model:
#      name: rf_lcld
#    detectors:
#      - name: n_batch
#        params:
#          batch_size: 5000
#      - name: rf_uncertainty
#        params:
#          uncertainty_type: aleatoric
#      - name: adwin
#        params: { }
#    label_delay: 10days
#    drift_delay: 00
#    retraining_delay: 1W
