---
window_size: 100000
performance:
  predict_forward: 50000
  n_jobs: 14
experience:
  random_state: 42
evaluation_params:
  batch_size: 25000
  rolling: False
  significance: 0.0
  metric:
    name: mcc
  n_score: 2
dataset:
  name: lcld_201317_ds_time
common_detectors_params:
  p_value: 0.01
  period: 5000
  ev_threshold: 0.99
  batch_size: 5000
common_runs_params:
  delays:
    label: 10days
    drift: 0
    retraining: 1W
