---
window_size: 100000
performance:
  predict_forward: 500000
  n_jobs: 10
experience:
  random_state: 42
evaluation_params:
  reference_methods:
    - no_drift
    - periodic
  batch_size: 5000
  rolling: False
  significance: 0.0
  metric:
    name: f1
  n_score: 2
dataset:
  name: lcld_v2_time
common_detectors_params:
  p_value: 0.05
  period: 5000
runs:
  - name: no_drift
    model:
      source: linear_model
      name: logistic_regression
    detectors:
      - name: no_drift
        params: {}
    label_delay: 0
    drift_delay: 0
    retraining_delay: 0
#  - name: periodic
#    model:
#      name: rf_lcld
#    detectors:
#      - name: periodic
#        params: {}
#    label_delay: 0
#    drift_delay: 0
#    retraining_delay: 0
#  - name: adwin_no_batch
#    model:
#      name: rf_lcld
#    detectors:
#      - name: adwin_error
#        params: {}
#    label_delay: 0
#    drift_delay: 0
#    retraining_delay: 0
#  - name: adwin_no_delay
#    model:
#      name: rf_lcld
#    detectors:
#      - name: n_batch
#        params:
#          batch_size: 5000
#      - name: adwin_error
#        params: { }
#    label_delay: 0
#    drift_delay: 0
#    retraining_delay: 0
#  - name: adwin
#    model:
#      name: rf_lcld
#    detectors:
#      - name: adwin_error
#        params: { }
#    label_delay: 10days
#    drift_delay: 0
#    retraining_delay: 1W
#  - name: data
#    model:
#      name: rf_lcld
#    detectors:
#      - name: n_batch
#        params:
#          batch_size: 5000
#      - name: evidently
#        params: {}
#    label_delay: 10days
#    drift_delay: 0
#    retraining_delay: 1W
#  - name: uncertainty_total
#    model:
#      name: rf_lcld
#    detectors:
#      - name: rf_uncertainty
#        params:
#          uncertainty_type: total
#      - name: adwin
#        params: {}
#    label_delay: 10days
#    drift_delay: 0
#    retraining_delay: 1W
#  - name: uncertainty_total_batch
#    model:
#      name: rf_lcld
#    detectors:
#      - name: n_batch
#        params:
#          batch_size: 5000
#      - name: rf_uncertainty
#        params:
#          uncertainty_type: total
#      - name: adwin
#        params: { }
#    label_delay: 10days
#    drift_delay: 0
#    retraining_delay: 1W
#  - name: uncertainty_epistemic_batch
#    model:
#      name: rf_lcld
#    detectors:
#      - name: n_batch
#        params:
#          batch_size: 5000
#      - name: rf_uncertainty
#        params:
#          uncertainty_type: epistemic
#      - name: adwin
#        params: { }
#    label_delay: 10days
#    drift_delay: 00
#    retraining_delay: 1W
#  - name: uncertainty_aleatoric_batch
#    model:
#      name: rf_lcld
#    detectors:
#      - name: n_batch
#        params:
#          batch_size: 5000
#      - name: rf_uncertainty
#        params:
#          uncertainty_type: aleatoric
#      - name: adwin
#        params: { }
#    label_delay: 10days
#    drift_delay: 00
#    retraining_delay: 1W
