---
runs:
# ------------ NO Drift
  - name: no_detection
    type: baseline
    detectors:
      - name: no_detection
# ------------ Periodic
  - name: periodic
    type: baseline
    detectors:
      - name: periodic
# ------------ Error Based
  - name: adwin_proba
    type: error
    detectors:
      - name: adwin
        params:
          metric_conf:
            name: proba_error
  - name: adwin_class
    type: error
    detectors:
      - name: adwin
        params:
          metric_conf:
            name: class_error
  - name: ddm_error
    type: error
    detectors:
      - name: ddm
  - name: eddm_error
    type: error
    detectors:
      - name: eddm
  - name: hddm_a_error
    type: error
    detectors:
      - name: hddm_a
  - name: hddm_w_error
    type: error
    detectors:
      - name: hddm_w
  - name: kswin_class_error
    type: error
    detectors:
      - name: kswin
        params:
          metric_conf:
            name: class_error
  - name: kswin_proba_error
    type: error
    detectors:
      - name: kswin
        params:
          metric_conf:
            name: proba_error
  - name: page_hinkley_class_error
    type: error
    detectors:
      - name: page_hinkley
        params:
          metric_conf:
            name: class_error
  - name: page_hinkley_proba_error
    type: error
    detectors:
      - name: page_hinkley
        params:
          metric_conf:
          name: proba_error
# --- DATA
  - name: data_evidently
    type: data
    detectors:
      - name: n_batch
      - name: evidently
  - name: pca_cd
    type: data
    detectors:
      - name: n_batch
      - name: pca_cd
  - name: pca_cd_js
    type: data
    detectors:
      - name: n_batch
      - name: pca_cd
  - name: tabular_alibi
    type: data
    detectors:
      - name: n_batch
      - name: tabular_alibi
## ------------ PREDICTIVE
  - name: aries_all
    type: predictive
    detectors:
      - name: n_batch
      - name: aries
      - name: adwin
