runs:
## ------------ PREDICTIVE
  - name: uncertainty_total
    type: predictive
    detectors:
      - name: n_batch
        params:
          batch_size: 5000
      - name: rf_uncertainty
        params:
          uncertainty_type: total
      - name: adwin
        params: { }
  - name: uncertainty_epistemic
    type: predictive
    detectors:
      - name: n_batch
        params: {}
      - name: rf_uncertainty
        params:
          uncertainty_type: epistemic
      - name: adwin
        params: { }
  - name: uncertainty_aleatoric
    type: predictive
    detectors:
      - name: n_batch
        params: {}
      - name: rf_uncertainty
        params:
          uncertainty_type: aleatoric
      - name: adwin
        params: { }
