---
runs:
# ------------ NO Drift
  - name: no_drift
    type: baseline
    detectors:
      - name: no_drift
        params: {}
## ------------ Periodic
  - name: periodic
    type: baseline
    detectors:
      - name: periodic
        params: {}
## ------------ Error Based
  - name: adwin_proba_error
    type: error
    detectors:
      - name: metric
        params:
          metric_conf:
            name: proba_error
      - name: adwin
        params: { }
  - name: adwin_error
    type: error
    detectors:
      - name: metric
        params:
          metric_conf:
            name: class_error
      - name: adwin
        params: { }
  - name: ddm_error
    type: error
    detectors:
      - name: metric
        params:
          metric_conf:
            name: class_error
      - name: ddm
        params: {}
  - name: eddm_error
    type: error
    detectors:
      - name: metric
        params:
          metric_conf:
            name: class_error
      - name: eddm
        params: {}
  - name: hddm_a_error
    type: error
    detectors:
      - name: metric
        params:
          metric_conf:
            name: class_error
      - name: hddm_a
        params: {}
  - name: hddm_w_error
    type: error
    detectors:
      - name: metric
        params:
          metric_conf:
            name: class_error
      - name: hddm_w
        params: {}
  - name: kswin_error
    type: error
    detectors:
      - name: metric
        params:
          metric_conf:
            name: class_error
      - name: kswin
        params: {}
  - name: kswin_proba_error
    type: error
    detectors:
      - name: metric
        params:
          metric_conf:
            name: proba_error
      - name: kswin
        params: {}
  - name: page_hinkley_error
    type: error
    detectors:
      - name: metric
        params:
          metric_conf:
            name: class_error
      - name: page_hinkley
        params: { }
  - name: page_hinkley_proba_error
    type: error
    detectors:
      - name: metric
        params:
          metric_conf:
            name: proba_error
      - name: page_hinkley
        params: {}
# --- DATA
  - name: data_evidently
    type: data
    detectors:
      - name: n_batch
        params: {}
      - name: evidently
        params: {}
  - name: pca_cd_intersection
    type: data
    detectors:
      - name: n_batch
        params: {}
      - name: pca_cd
        params:
          divergence_metric: intersection
  - name: pca_cd_js
    type: data
    detectors:
      - name: n_batch
        params: {}
      - name: pca_cd
        params:
          divergence_metric: js
  - name: pca_cd_mkl
    type: data
    detectors:
      - name: n_batch
        params: {}
      - name: pca_cd
        params:
          divergence_metric: mkl
  - name: ks_test
    type: data
    detectors:
      - name: n_batch
        params: {}
      - name: ks_test
        params: {}
  - name: tabular_alibi_bonferroni
    type: data
    detectors:
      - name: n_batch
        params: {}
      - name: tabular_alibi
        params:
          correction: bonferroni
  - name: tabular_alibi_fdr
    type: data
    detectors:
      - name: n_batch
        params: {}
      - name: tabular_alibi
        params:
          correction: fdr
  - name: mmd
    type: data
    detectors:
      - name: n_batch
        params: {}
      - name: mmd
        params: {}
## ------------ PREDICTIVE
  - name: aries_all
    type: predictive
    detectors:
      - name: n_batch
        params: {}
      - name: aries
        params:
          acc: 0
      - name: adwin
        params: {}
  - name: aries_acc_1
    type: predictive
    detectors:
      - name: n_batch
        params: {}
      - name: aries
        params:
          acc: 1
      - name: adwin
        params: {}
  - name: aries_acc_2
    type: predictive
    detectors:
      - name: n_batch
        params: {}
      - name: aries
        params:
          acc: 2
      - name: adwin
        params: {}
