---
name: electricity
dataset:
  name: electricity
model:
  source: drift_study.model_arch.tree_model
  name: rf_scaled
  metadata: true
schedules:
  - name: divergence
    detectors:
      - name: n_batch
        params:
          batch_size: 480
      - name: divergence
first_train_window_size: -1
train_window_size: -1
train_window_sizes: [4380, 8760, 17520, 35040, -1]
periods: [480, 960, 1920, 3840, 7680, 15360, 30720]
test_start_idx: 17520
training_step_size: 480
common_detectors_params:
  - batch_size: 480
delays:
  drift: 0
  label: 10days
  retraining: 4W
optimization_iter:
  model: 25
  detector: 25
optimization_splits:
  detector: 4
metric:
  name: mcc
predict_forward: 1000
performance:
  n_jobs:
    detector_optimization: 1
trial_params: {}
use_auto_model_tuning: true
