---
name: electricity
dataset:
  name: electricity
model:
  source: drift_study.model_arch.mlp_rln
  name: torchrln
  metadata: true
  metric: mcc
  params:
    objective: classification
    batch_size: 64
    epochs: 100
    early_stopping_rounds: 5
    num_classes: 2
    class_weight: balanced
    hidden_dim: 10
    n_layers: 10
first_train_window_size: -1
train_window_sizes: [4440, 8880, 17760, 35520, -1]
periods: [480, 960, 1920, 3840, 7680, 15360, 30720]
test_start_idx: 17760
training_step_size: 480
common_detectors_params:
  batch_size: 480
delays:
  drift: 0
  label: 1days
  retraining: 9days
optimization_iter:
  model: 25
  detector: 25
optimization_splits:
  detector: 4
metric:
  name: mcc
predict_forward: 1000
evaluation:
  batch_size: 480
performance:
  n_jobs:
    detector_optimization: 32
    detector: 32
trial_params:
  model_type: random_forest
logger_config_path: ./config/default_logger_config.yaml
models_dir: ./data/drift_202402/models