---
name: lcld_201317_ds_time
dataset:
  name: lcld_201317_ds_time
model:
  source: drift_study.model_arch.mlp_rln
  name: torchrln
  metadata: true
  metric: mcc
  params:
    objective: classification
    batch_size: 1024
    epochs: 100
    early_stopping_rounds: 5
    num_classes: 2
    class_weight: balanced
first_train_window_size: -1
train_window_size: 400000
train_window_sizes: [20000, 50000, 100000, 200000, 400000]
periods: [5000, 10000, 20000, 50000, 100000, 200000, 400000]
test_start_idx: 400000
training_step_size: 5000
common_detectors_params:
  batch_size: 5000
delays:
  drift: 0
  label: 10days
  retraining: 4W
optimization_iter:
  model: 25
  detector: 25
optimization_splits:
  detector: 4
metric:
  name: mcc
predict_forward: 1000
evaluation:
  batch_size: 5000
performance:
  n_jobs:
    detector_optimization: 32
    detector: 32
trial_params: {}
logger_config_path: ./config/default_logger_config.yaml
